#index:
#    path: /
#    controller: App\Controller\DefaultController::index
upload_image:
    path: /upload-image
    controller: 'App\Controller\UserController::uploadImageForm'
    methods: [GET, POST]